# TODO:
# 2. Block docker image creation for non-related changes.
# 3. Extend a base YAML template and override the parameters as necessary. Move the common tasks to the template.
# 4. Trigger the deployment changes in the template dynamically based on branch and specific path changes

name: CI/CD Pipeline

on:
  schedule:
    # - cron: '30 5 * * 1' # Monday
    - cron: '35 10 * * *'
    - cron: '37 10 * * *'

  push:
    branches:
      - main
      - master
      - overall_requirement_basecode
      - data_collection_updates
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKENS }}
        
      - name: Build and push Docker images
        run: |
          # TODO: Move to env variables
          VERSION=1.0.1
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          VERSION_TAG="$VERSION-$BUILD_NUMBER"

          # Build and push Docker image for data collection
          docker build -t ml-data-collection-service:${VERSION_TAG} \
            --label "Simulates weekly sensor data collection and uploads to Google Cloud." \
            -f dockerfiles/DatacollectionDockerFile .

          docker tag ml-data-collection-service:${VERSION_TAG} \
            ${{ secrets.DOCKER_USERNAME }}/ml-data-collection-service:${VERSION_TAG}

          docker push ${{ secrets.DOCKER_USERNAME }}/ml-data-collection-service:${VERSION_TAG}

          # Build and push Docker image for data transfer
          docker build -t ml-data-transfer-service:${VERSION_TAG} \
            --label "Transfers locally simulated data to Google Cloud Storage." \
            -f dockerfiles/DataTransferDockerFile .

          docker tag ml-data-transfer-service:${VERSION_TAG} \
            ${{ secrets.DOCKER_USERNAME }}/ml-data-transfer-service:${VERSION_TAG}

          docker push ${{ secrets.DOCKER_USERNAME }}/ml-data-transfer-service:${VERSION_TAG}

  data_collection:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKENS }}

      - name: Not at 10:27 AM
        if: github.event.schedule == '37 10 * * *'
        run: echo "This step will be skipped at '37 10 * * *'"
  
      - name: Run Docker container
        if: github.event.schedule == '35 10 * * *'
        run: |
          # TODO: Move to env variables
          VERSION=1.0.1
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          VERSION_TAG="$VERSION-$BUILD_NUMBER"

          docker run -d --name ml-data-collection \
            ${{ secrets.DOCKER_USERNAME }}/ml-data-collection-service:${VERSION_TAG} || true          

  data_transfer:
    runs-on: ubuntu-latest

    needs: data_collection  # Ensure the data collection job has completed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKENS }}

      - name: Not at 10:25 AM
        if: github.event.schedule == '35 10 * * *'
        run: echo "This step will be skipped at '35 10 * * *'"
  
      - name: Run Docker container for data transfer
        if: github.event.schedule == '37 10 * * *'
        run: |
          VERSION=1.0.1
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          VERSION_TAG="$VERSION-$BUILD_NUMBER"

          docker run -d --name ml-data-transfer \
            ${{ secrets.DOCKER_USERNAME }}/ml-data-transfer-service:${VERSION_TAG} || true
          